name=input ("I am going to ask you a few questions, what is your name?")
food=input ("What is your favourite food?")
film=input ("What is your favourite film?")
sport=input ("What is your favourite sport?")
team=input ("What sports team do you support?")
print ("I am going to repeat your answers.")
print ("Your favourite food is", food)
print ("Your favourite film is", film)
print ("Your favourite sport is", sport)
print ("You support", team)
print ("Thankyou", name,"BYE")
